#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "koel"
name = "Koel"
description.en = "Simple web-based personal audio streaming service"
description.fr = "Simple service web de streaming audio personnel"

version = "9.0.0~ynh1"

maintainers = ["tituspijean"]

[upstream]
license = "MIT"
website = "https://koel.dev"
demo = "https://demo.koel.dev"
admindoc = "https://docs.koel.dev"
code = "https://github.com/koel/koel"
cpe = "cpe:2.3:a:koel:koel"
fund = "https://opencollective.com/koel"

[integration]
yunohost = ">= 12.1.38"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "300M"
ram.build = "150M"
ram.runtime = "150M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

    [resources.sources.main]
    url = "https://github.com/koel/koel/releases/download/v9.0.0/koel-v9.0.0.tar.gz"
    sha256 = "ac3b2559d79eba88e92d306fb5de4d2cca5c38aa20d0f2bfa48ea4e29e98f448"

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset = "^koel-v.*tar.gz$"

    [resources.system_user]
    allow_email = true

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"
    main.auth_header = false

    [resources.ports]

    [resources.apt]
    packages = [
        "php8.5-fpm",
        "php8.5-gd",
        "php8.5-mbstring",
        "php8.5-mysql",
        "php8.5-sqlite3",
        "php8.5-xml",
        "mariadb-server",
        "ffmpeg",
    ]

    [resources.database]
    type = "mysql"
